In [2]:
import pandas as pd

In [9]:
import os

print("current folder:")
print(os.listdir())

current folder:
['01_data_understanding.ipynb']

In [10]:
print(os.listdir("../data/raw/"))

['qlfs_2025_q4']

In [20]:
import os

print("Current working directory:")
print(os.getcwd())

Current working directory:
c:\Users\Admin\OneDrive - Sol Plaatje University\Desktop\UnemploymentAnalysis\sa-youth-unemployment-analysis\notebooks

In [21]:
import os

print(os.listdir("../data/raw/qlfs_2025_q4"))

['q-qlfs-2025-q4_pdf (1).pdf', 'qlfs-2025-q4-concepts-and-definitions.pdf', 'qlfs-2025-q4-guide.pdf', 'qlfs-2025-q4-metadata.pdf', 'qlfs-2025-q4-release_pdf.pdf', 'qlfs-2025-q4-v1.csv', 'qlfs-2025-q4-v1.dta']

In [3]:
df = pd.read_csv("../data/raw/qlfs_2025_q4/qlfs-2025-q4-v1.csv")

In [25]:
df.head()

,UQNO,SURVEYDATE,PERSONNO,Q12NIGHTS,Q13GENDER,Q14DAY,Q14MONTH,Q14YEAR,Q14AGE,Q15POPULATION,...,Underempl,Hrswrk,Education_status,Neet,Graduates,Ste_icse93,Ste_icse18_authority,Ste_icse18,Ste_icse18_risk,Weight
0,160100880000001801,4112025,1,1,1,2,7,1996,29,4,...,2.0,45.0,6,2.0,3,1.0,4.0,8.0,5.0,3393.655742
1,160100880000001801,4112025,2,1,2,16,2,1998,27,4,...,2.0,35.0,6,2.0,4,1.0,4.0,8.0,5.0,3393.655742
2,160100880000001801,4112025,3,1,1,24,1,2024,1,4,...,NaN,NaN,1,NaN,1,NaN,NaN,NaN,NaN,3393.655742
3,160100880000005801,4112025,2,1,2,10,7,1977,48,4,...,2.0,40.0,5,2.0,2,1.0,4.0,8.0,5.0,1382.700384
4,160100880000005801,4112025,3,1,2,23,5,2016,9,4,...,NaN,NaN,2,NaN,1,NaN,NaN,NaN,NaN,1382.700384

In [26]:
df.head()

,UQNO,SURVEYDATE,PERSONNO,Q12NIGHTS,Q13GENDER,Q14DAY,Q14MONTH,Q14YEAR,Q14AGE,Q15POPULATION,...,Underempl,Hrswrk,Education_status,Neet,Graduates,Ste_icse93,Ste_icse18_authority,Ste_icse18,Ste_icse18_risk,Weight
0,160100880000001801,4112025,1,1,1,2,7,1996,29,4,...,2.0,45.0,6,2.0,3,1.0,4.0,8.0,5.0,3393.655742
1,160100880000001801,4112025,2,1,2,16,2,1998,27,4,...,2.0,35.0,6,2.0,4,1.0,4.0,8.0,5.0,3393.655742
2,160100880000001801,4112025,3,1,1,24,1,2024,1,4,...,NaN,NaN,1,NaN,1,NaN,NaN,NaN,NaN,3393.655742
3,160100880000005801,4112025,2,1,2,10,7,1977,48,4,...,2.0,40.0,5,2.0,2,1.0,4.0,8.0,5.0,1382.700384
4,160100880000005801,4112025,3,1,2,23,5,2016,9,4,...,NaN,NaN,2,NaN,1,NaN,NaN,NaN,NaN,1382.700384

In [29]:
df.columns

Index(['UQNO', 'SURVEYDATE', 'PERSONNO', 'Q12NIGHTS', 'Q13GENDER', 'Q14DAY',
       'Q14MONTH', 'Q14YEAR', 'Q14AGE', 'Q15POPULATION',
       ...
       'Underempl', 'Hrswrk', 'Education_status', 'Neet', 'Graduates',
       'Ste_icse93', 'Ste_icse18_authority', 'Ste_icse18', 'Ste_icse18_risk',
       'Weight'],
      dtype='object', length=200)

In [31]:
df.shape

(63264, 200)

In [32]:
df.info

<bound method DataFrame.info of                      UQNO  SURVEYDATE  PERSONNO  Q12NIGHTS  Q13GENDER  Q14DAY  \
0      160100880000001801     4112025         1          1          1       2
1      160100880000001801     4112025         2          1          2      16
2      160100880000001801     4112025         3          1          1      24
3      160100880000005801     4112025         2          1          2      10
4      160100880000005801     4112025         3          1          2      23
...                   ...         ...       ...        ...        ...     ...
63259  987105900000013101     4112025         2          1          1      29
63260  987105900000013101     4112025         3          1          2      24
63261  987105900000013101     4112025         4          1          1      29
63262  987105900000013101     4112025         5          1          2      28
63263  987105900000013101     4112025         6          1          2      11

       Q14MONTH  Q14YEAR  Q14AGE  Q15POPULATION  ...  Underempl  Hrswrk  \
0             7     1996      29              4  ...        2.0    45.0
1             2     1998      27              4  ...        2.0    35.0
2             1     2024       1              4  ...        NaN     NaN
3             7     1977      48              4  ...        2.0    40.0
4             5     2016       9              4  ...        NaN     NaN
...         ...      ...     ...            ...  ...        ...     ...
63259         3     1987      38              1  ...        NaN     NaN
63260         7     1994      31              1  ...        NaN     NaN
63261         9     2008      17              1  ...        NaN     NaN
63262         2     2016       9              1  ...        NaN     NaN
63263         9     2022       3              1  ...        NaN     NaN

       Education_status  Neet  Graduates  Ste_icse93  Ste_icse18_authority  \
0                     6   2.0          3         1.0                   4.0
1                     6   2.0          4         1.0                   4.0
2                     1   NaN          1         NaN                   NaN
3                     5   2.0          2         1.0                   4.0
4                     2   NaN          1         NaN                   NaN
...                 ...   ...        ...         ...                   ...
63259                 4   1.0          1         NaN                   NaN
63260                 5   1.0          2         NaN                   NaN
63261                 3   2.0          1         NaN                   NaN
63262                 2   NaN          1         NaN                   NaN
63263                 1   NaN          1         NaN                   NaN

       Ste_icse18  Ste_icse18_risk       Weight
0             8.0              5.0  3393.655742
1             8.0              5.0  3393.655742
2             NaN              NaN  3393.655742
3             8.0              5.0  1382.700384
4             NaN              NaN  1382.700384
...           ...              ...          ...
63259         NaN              NaN   820.297974
63260         NaN              NaN   820.297974
63261         NaN              NaN   820.297974
63262         NaN              NaN   820.297974
63263         NaN              NaN   820.297974

[63264 rows x 200 columns]>

In [34]:
df.describe(include="all")

,UQNO,SURVEYDATE,PERSONNO,Q12NIGHTS,Q13GENDER,Q14DAY,Q14MONTH,Q14YEAR,Q14AGE,Q15POPULATION,...,Underempl,Hrswrk,Education_status,Neet,Graduates,Ste_icse93,Ste_icse18_authority,Ste_icse18,Ste_icse18_risk,Weight
count,6.326400e+04,6.326400e+04,63264.000000,63264.0,63264.000000,63264.000000,63264.000000,63264.000000,63264.000000,63264.000000,...,15839.000000,15838.000000,63264.000000,46032.000000,63264.000000,15839.000000,15839.000000,15839.000000,15839.000000,63264.000000
mean,6.099660e+17,4.111716e+06,3.050487,1.0,1.523378,14.563812,6.305956,1993.720599,31.159554,1.288189,...,1.955048,42.174264,3.563306,1.489681,1.467928,1.302607,3.623209,7.563735,4.345476,977.326676
std,2.556642e+17,8.045423e+03,2.319734,0.0,0.499457,9.081415,3.504148,21.153586,21.154401,0.750761,...,0.207206,12.634428,1.607428,0.499899,0.831399,0.695202,0.856893,1.770295,1.428552,529.222921
min,1.601009e+17,4.102025e+06,1.000000,1.0,1.000000,1.000000,1.000000,1910.000000,0.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,50.000000
25%,3.751006e+17,4.102025e+06,1.000000,1.0,1.000000,7.000000,3.000000,1979.000000,13.000000,1.000000,...,2.000000,40.000000,2.000000,1.000000,1.000000,1.000000,4.000000,8.000000,5.000000,631.610439
50%,5.991411e+17,4.112025e+06,2.000000,1.0,2.000000,14.000000,6.000000,1997.000000,28.000000,1.000000,...,2.000000,40.000000,4.000000,1.000000,1.000000,1.000000,4.000000,8.000000,5.000000,904.626868
75%,7.991141e+17,4.122025e+06,4.000000,1.0,2.000000,22.000000,9.000000,2012.000000,46.000000,1.000000,...,2.000000,48.000000,5.000000,2.000000,2.000000,1.000000,4.000000,8.000000,5.000000,1229.699146
max,9.871059e+17,4.122025e+06,26.000000,1.0,2.000000,31.000000,12.000000,2025.000000,115.000000,4.000000,...,2.000000,112.000000,7.000000,2.000000,5.000000,4.000000,5.000000,13.000000,5.000000,5252.356413

In [4]:
df.columns.to_list()

['UQNO',
 'SURVEYDATE',
 'PERSONNO',
 'Q12NIGHTS',
 'Q13GENDER',
 'Q14DAY',
 'Q14MONTH',
 'Q14YEAR',
 'Q14AGE',
 'Q15POPULATION',
 'Q16MARITALSTATUS',
 'Q17EDUCATION',
 'Q18FIELD',
 'Q19ATTE',
 'Q110EDUI',
 'Q111APPRENTICE',
 'Q112TRAIN',
 'Q20SELFRESPOND',
 'Q24APDWRK',
 'Q24BOWNBUSNS',
 'Q24CUNPDWRK',
 'Q25APDWRK',
 'Q27RSNABSENT',
 'Q27OFFSEASON',
 'Q27ATIME',
 'Q27BRECPAY',
 'Q2801CROPS',
 'Q2802ANIMALS',
 'Q2803FISHING',
 'Q2804NONE',
 'Q2901CROPS',
 'Q2902ANIMALS',
 'Q2903FISHING',
 'Q2904JOB',
 'Q210MARKET',
 'Q211HIRE',
 'Q212SUBINDUSTRY',
 'Q31ALOOKWRK',
 'Q31BSTARTBUSNS',
 'Q3201REGISTER',
 'Q3202ENQUIRE',
 'Q3203JOBADS',
 'Q3204JOBSEARCH',
 'Q3205ASSISTANCE',
 'Q3206STARTBUSNS',
 'Q3207CASUAL',
 'Q3208FINASSIST',
 'Q33HAVEJOB',
 'Q33AWHNSTART',
 'Q34WANTTOWRK',
 'Q35YNOTWRK',
 'Q36TIMESEEK',
 'Q37ACTPRIORJOBSEEK',
 'Q38RSNNOTSEEK',
 'Q39JOBOFFER',
 'Q311RSNNOTAVAILABLE',
 'Q311bWHNSTART',
 'Q312EVERWRK',
 'Q313TIMEUNEMPLOY',
 'Q314RSNSTOPWRK',
 'Q315PREVOCCUPATION',
 'Q316PREVINDUSTRY',
 'Q317WRK4WHOM',
 'Q319aODDJOBS',
 'Q319bINHHPERS',
 'Q319cNOTHHPERS',
 'Q319dCHARITY',
 'Q319eUIF',
 'Q319fSAVINGS',
 'Q319gPENSION',
 'Q319hGRANTS',
 'Q319iWELFARE',
 'Q319jOTHER',
 'Q41MULTIPLEJOBS',
 'Q42OCCUPATION',
 'Q43INDUSTRY',
 'Q44YEARSTART',
 'Q44MONTHSTART',
 'Q45WRK4WHOM',
 'Q45aDECISON',
 'Q45b01WAGE',
 'Q45b02PIECEWRK',
 'Q45b03COMM',
 'Q45b04TIPS',
 'Q45b05FEESERV',
 'Q45b06MEALS',
 'Q45b07PRODUCTS',
 'Q45b08CASHPAY',
 'Q45b09NOTPAID',
 'Q46PENSION',
 'Q46APENSIONSELF',
 'Q47PDLEAVE',
 'Q47B1PDSICK',
 'Q47B2MATERNITY',
 'Q48UIF',
 'Q49MEDICAL',
 'Q410INCOMETAX',
 'Q411CONTRACTTYPE',
 'Q412CONTRDURATION',
 'Q412ACONTRPERIOD',
 'Q412AiiCONMINIMUM',
 'Q412BMEMUNION',
 'Q412CSALINCREMENT',
 'Q412dTYPEBUSNS',
 'Q413aHIRE',
 'Q413bREGISTER',
 'Q413cCORPORATION',
 'Q413C1SINGLECLIENT',
 'Q413C2SOURCECLIENT',
 'Q413C3MAKEPROD',
 'Q413C3SELLPROD',
 'Q413C3MATERIALS',
 'Q413C3NONE',
 'Q413C4SETPRICE',
 'Q413C4DECIDEHOW',
 'Q413C4NONE',
 'Q413VAT',
 'Q414TAX',
 'Q414bBOOKTYPE',
 'Q414cPENSION_DC',
 'Q415PLACE',
 'Q416NRWORKERS',
 'Q418HRSWRK',
 'Q419MONHRSWRK',
 'Q419TUEHRSWRK',
 'Q419WEDHRSWRK',
 'Q419THUHRSWRK',
 'Q419FRIHRSWRK',
 'Q419SATHRSWRK',
 'Q419SUNHRSWRK',
 'Q419TOTALHRS',
 'Q420FIRSTHRSWRK',
 'Q420SECONDHRSWRK',
 'Q420OTHERHRSWRK',
 'Q420TOTALHRSWRK',
 'Q4211MONHRSWRK',
 'Q4211TUEHRSWRK',
 'Q4211WEDHRSWRK',
 'Q4211THUHRSWRK',
 'Q4211FRIHRSWRK',
 'Q4211SATHRSWRK',
 'Q4211SUNHRSWRK',
 'Q4211TOTALHRS',
 'Q4212MONHRSWRK',
 'Q4212TUEHRSWRK',
 'Q4212WEDHRSWRK',
 'Q4212THUHRSWRK',
 'Q4212FRIHRSWRK',
 'Q4212SATHRSWRK',
 'Q4212SUNHRSWRK',
 'Q4212TOTALHRS',
 'Q4213MONHRSWRK',
 'Q4213TUEHRSWRK',
 'Q4213WEDHRSWRK',
 'Q4213THUHRSWRK',
 'Q4213FRIHRSWRK',
 'Q4213SATHRSWRK',
 'Q4213SUNHRSWRK',
 'Q4213TOTALHRS',
 'Q422MOREHRS',
 'Q423ADDHRS',
 'Q424WRKXHRS',
 'Q425STARTXWRK',
 'Q59AFARMWRK',
 'Q59ATIME',
 'Q59BFETCHWATER',
 'Q59BTIME',
 'Q59CPRODHHGOODS',
 'Q59CTIME',
 'Q59DCONSTRUC',
 'Q59DTIME',
 'Q59ECATCHFOOD',
 'Q59ETIME',
 'Province',
 'Metro_code',
 'Geo_Type_Code',
 'Stratum',
 'Age_grp1',
 'Status',
 'Lfs_Status',
 'InactReason',
 'Unempl_Status',
 'Indus',
 'Occup',
 'PrevIndus',
 'PrevOccup',
 'Sector',
 'Infempl',
 'Long_term_unempl',
 'at_least_1',
 'Underempl',
 'Hrswrk',
 'Education_status',
 'Neet',
 'Graduates',
 'Ste_icse93',
 'Ste_icse18_authority',
 'Ste_icse18',
 'Ste_icse18_risk',
 'Weight']

In [6]:
print("Sum of null cells>>>")
df.isnull().sum()

Sum of null cells>>>

UQNO                        0
SURVEYDATE                  0
PERSONNO                    0
Q12NIGHTS                   0
Q13GENDER                   0
                        ...
Ste_icse93              47425
Ste_icse18_authority    47425
Ste_icse18              47425
Ste_icse18_risk         47425
Weight                      0
Length: 200, dtype: int64

In [7]:
print("Sum of duplicates>>")
df.duplicated().sum()

Sum of duplicates>>

np.int64(0)

In [8]:
print("Uniques")
df.nunique()

Uniques

UQNO                    19945
SURVEYDATE                  3
PERSONNO                   26
Q12NIGHTS                   1
Q13GENDER                   2
                        ...
Ste_icse93                  4
Ste_icse18_authority        5
Ste_icse18                 11
Ste_icse18_risk             5
Weight                  17366
Length: 200, dtype: int64